version: '3'
services:  
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=potluck
      - POSTGRES_PASSWORD=potluck
      - POSTGRES_DB=potluck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U potluck"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=potluck
      - DB_USER=potluck
      - DB_PASS=potluck
      - HOST=localhost
      - PORT=8080
      - PASSWORD=password
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db:
    driver: local
